### ISSUE TITLE
Question about the shape of M[i, j]

### ISSUE THREAD

**Issue by cxzhou95** [zhangyi-3/KBNet#1]
For group convolution, if both input and output have the shape of  H * W * C, and the number of groups is 4, the kernel size is k, then for each location, the weight should have the shape of C/4 * k * k * C/4 * 4  = C * (C/4) * k^2. But in paper, M[i, j] have the shape of C * 4 * k^2.

**Comment by zhangyi-3** [comment]
Thanks for your question. The group number should be C / 4. I will revise the paper to make it clear.
