### ISSUE TITLE
The SSIM of the SIDD does not match 

### ISSUE THREAD

**Issue by Cynicarlos** [zhangyi-3/KBNet#9]
**Dear author:**
As I show here :

![results_paper](https://github.com/zhangyi-3/KBNet/assets/77565463/8a76d3e2-6d07-4155-8ece-f39ee21f6a58)

![result_test](https://github.com/zhangyi-3/KBNet/assets/77565463/912151a1-706d-4547-b18f-cbac11f94d55)

The PSNR matches with the relults in your paper, but the SSIM does not. What is wrong?

Thank you!

**Comment by jacky22043** [comment]
Hello, I get the same results in paper. Here is my setting:
![denoise_SIDD](https://github.com/zhangyi-3/KBNet/assets/44692416/5d9b5102-3493-49ea-9e13-7e5cabd2484c)
1. Download SIDD validation data, run
`python download_data.py --noise real --data test --dataset SIDD`
2. Download the Denoise folder pre-trained [models](https://mycuhk-my.sharepoint.com/:f:/g/personal/1155135732_link_cuhk_edu_hk/EofsV3eVcAxNlrW72JXqzRUBhkM1Mzw50pJ3BHlAyMYnVw?e=MeMB5H).
2.1 Replace all files in denoise to the location of KBNet-main\Denoising.
3. And make sure copy the basicsr folder under root folder to Denoising folder.

**Comment by whhwhhhh** [comment]
Where to download sidd.pth,I can't find it 
![Uploading 649.jpg…]()

**Comment by whhwhhhh** [comment]
Where to download sidd.pth,I can't find it
![650](https://github.com/zhangyi-3/KBNet/assets/130810279/175bb147-e56e-473f-9dd1-bc8ab816bc46)

**Comment by Cynicarlos** [comment]
> Where to download sidd.pth,I can't find it ![650](https://private-user-images.githubusercontent.com/130810279/311481861-175bb147-e56e-473f-9dd1-bc8ab816bc46.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDUzODMsIm5iZiI6MTcxMDA0NTA4MywicGF0aCI6Ii8xMzA4MTAyNzkvMzExNDgxODYxLTE3NWJiMTQ3LWU1NmUtNDczZi05ZGQxLWJjOGFiODE2YmM0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNDMxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmNiYWY3MDQ1ODczYTA2YzczY2QwYTMwZWRiYTA0ODQ0NzIxODYyMTI3Zjg1MGY0OTBjNDJlM2FiMmFhYWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DhvVnLB7LTJZM9vmDBsgIVMvbalPag1Zk_RF1PwNiOk)

![image](https://github.com/zhangyi-3/KBNet/assets/77565463/1ea472d3-a7c3-4382-9e48-b1482c5cc46a)

**Comment by whhwhhhh** [comment]
thanks


---Original---
From: ***@***.***&gt;
Date: Sun, Mar 10, 2024 12:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhangyi-3/KBNet] The SSIM of the SIDD does not match  (Issue #9)




  
Where to download sidd.pth,I can't find it 
  
image.png (view on web)
 
&mdash;

**Comment by whhwhhhh** [comment]
OOPS。。。。。I still can't find this ,can you share me zhe link or url?

**Comment by Cynicarlos** [comment]
> OOPS。。。。。I still can't find this ,can you share me zhe link or url?

https://mycuhk-my.sharepoint.com/personal/1155135732_link_cuhk_edu_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2F1155135732%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2Fshare%2FKBNet%2FDenoising%2Fpretrained%5Fmodels

**Comment by whhwhhhh** [comment]
![652](https://github.com/zhangyi-3/KBNet/assets/130810279/d6521924-b397-4568-9d88-8867fba68eed)
eemmmmm，maybe something is wrong

**Comment by Cynicarlos** [comment]
> ![652](https://private-user-images.githubusercontent.com/130810279/311494829-d6521924-b397-4568-9d88-8867fba68eed.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTk2OTQsIm5iZiI6MTcxMDA1OTM5NCwicGF0aCI6Ii8xMzA4MTAyNzkvMzExNDk0ODI5LWQ2NTIxOTI0LWIzOTctNDU2OC05ZDg4LTg4NjdmYmE2OGVlZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwODI5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTRmNmQ1MzM4ODg4Zjc0MTFjNDhmMDU5NTRhMWUwYzZiMmY2NWFjNWJkZmFmMDM3NGFiNjdlNDcyMjI4Yjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.faU4AmdfoIzhf9ko4Y67-2-Uh4kG3FrLB6-JPGed0h4) eemmmmm，maybe something is wrong

The author gave the link in https://github.com/zhangyi-3/KBNet/blob/main/Denoising/README.md#Real-Image-Denoising
you can find all models there
